SINGLE:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "SINGLE/3to50deg/e-.csv"
        - "SINGLE/3to50deg/pi-.csv"
        - "SINGLE/45to135deg/e-.csv"
        - "SINGLE/45to135deg/pi-.csv"
        - "SINGLE/130to177deg/e-.csv"
        - "SINGLE/130to177deg/pi-.csv"

SINGLE:timings:
  extends: .timings_all
  needs: 
    - SINGLE:nevents
  parallel:
    matrix:
      - DATA:
        - "SINGLE/3to50deg/e-.csv"
        - "SINGLE/3to50deg/pi-.csv"
        - "SINGLE/45to135deg/e-.csv"
        - "SINGLE/45to135deg/pi-.csv"
        - "SINGLE/130to177deg/e-.csv"
        - "SINGLE/130to177deg/pi-.csv"

SINGLE:collect:
  extends: .collect
  needs: 
    - SINGLE:timings
