DIS:NC:10x275:gzip:
  extends: .gzip
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/10x275/minQ2=1000/DIS_NC_10x275_minQ2=1000.csv"
        - "DIS/NC/10x275/minQ2=100/DIS_NC_10x275_minQ2=100.csv"
        - "DIS/NC/10x275/minQ2=10/DIS_NC_10x275_minQ2=10.csv"
        - "DIS/NC/10x275/minQ2=1/DIS_NC_10x275_minQ2=1.csv"

DIS:NC:10x275:nevents:
  extends: .nevents
  needs:
    - DIS:NC:10x275:gzip
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/10x275/minQ2=1000/DIS_NC_10x275_minQ2=1000.csv"
        - "DIS/NC/10x275/minQ2=100/DIS_NC_10x275_minQ2=100.csv"
        - "DIS/NC/10x275/minQ2=10/DIS_NC_10x275_minQ2=10.csv"
        - "DIS/NC/10x275/minQ2=1/DIS_NC_10x275_minQ2=1.csv"

DIS:NC:10x275:timings:
  extends: .timings
  needs: 
    - DIS:NC:10x275:nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/10x275/minQ2=1000/DIS_NC_10x275_minQ2=1000.csv"
        - "DIS/NC/10x275/minQ2=100/DIS_NC_10x275_minQ2=100.csv"
        - "DIS/NC/10x275/minQ2=10/DIS_NC_10x275_minQ2=10.csv"
        - "DIS/NC/10x275/minQ2=1/DIS_NC_10x275_minQ2=1.csv"

DIS:NC:10x275:collect:
  extends: .collect
  needs: 
    - DIS:NC:10x275:timings
