SIDIS:pythia6-eic:1.3.0:ep_noradcor:9x130:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "SIDIS/pythia6-eic/1.3.0/ep_noradcor/9x130/pythia6-eic_1.3.0_ep_noradcor_9x130_q2_0to1.csv"
        - "SIDIS/pythia6-eic/1.3.0/ep_noradcor/9x130/pythia6-eic_1.3.0_ep_noradcor_9x130_q2_1to10.csv"
        - "SIDIS/pythia6-eic/1.3.0/ep_noradcor/9x130/pythia6-eic_1.3.0_ep_noradcor_9x130_q2_10to100.csv"
        - "SIDIS/pythia6-eic/1.3.0/ep_noradcor/9x130/pythia6-eic_1.3.0_ep_noradcor_9x130_q2_100to1000.csv"
        - "SIDIS/pythia6-eic/1.3.0/ep_noradcor/9x130/pythia6-eic_1.3.0_ep_noradcor_9x130_q2_1000to100000.csv"

SIDIS:pythia6-eic:1.3.0:ep_noradcor:9x130:timings:
  extends: .timings
  needs:
    - SIDIS:pythia6-eic:1.3.0:ep_noradcor:9x130:nevents
  parallel:
    matrix:
      - DATA:
        - "SIDIS/pythia6-eic/1.3.0/ep_noradcor/9x130/pythia6-eic_1.3.0_ep_noradcor_9x130_q2_0to1.csv"
        - "SIDIS/pythia6-eic/1.3.0/ep_noradcor/9x130/pythia6-eic_1.3.0_ep_noradcor_9x130_q2_1to10.csv"
        - "SIDIS/pythia6-eic/1.3.0/ep_noradcor/9x130/pythia6-eic_1.3.0_ep_noradcor_9x130_q2_10to100.csv"
        - "SIDIS/pythia6-eic/1.3.0/ep_noradcor/9x130/pythia6-eic_1.3.0_ep_noradcor_9x130_q2_100to1000.csv"
        - "SIDIS/pythia6-eic/1.3.0/ep_noradcor/9x130/pythia6-eic_1.3.0_ep_noradcor_9x130_q2_1000to100000.csv"

SIDIS:pythia6-eic:1.3.0:ep_noradcor:9x130:collect:
  extends: .collect
  needs:
    - SIDIS:pythia6-eic:1.3.0:ep_noradcor:9x130:timings
