DDIS:ep:ewRad:9x130:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "DDIS/ep/ewRad/9x130/rapgap3.310-2.0_ddis_ep_ewRad_9x130_q2_5to1e8.csv"

DDIS:ep:ewRad:9x130:timings:
  extends: .timings
  needs:
    - DDIS:ep:ewRad:9x130:nevents
  parallel:
    matrix:
      - DATA:
        - "DDIS/ep/ewRad/9x130/rapgap3.310-2.0_ddis_ep_ewRad_9x130_q2_5to1e8.csv"

DDIS:ep:ewRad:9x130:collect:
  extends: .collect
  needs:
    - DDIS:ep:ewRad:9x130:timings
