EXCLUSIVE:DIFFRACTIVE_PHI:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DIFFRACTIVE_PHI/Sartre_Coherent.csv"
        - "EXCLUSIVE/DIFFRACTIVE_PHI/Sartre_Coherent_q2_15.csv"
        - "EXCLUSIVE/DIFFRACTIVE_PHI/Sartre_Incoherent.csv"
        - "EXCLUSIVE/DIFFRACTIVE_PHI/sartre1.39-1.0_coherent_phi_eAu_bsat_10x100.csv"
        - "EXCLUSIVE/DIFFRACTIVE_PHI/eSTARlight/eSTARlight1.2.0-1.0_coherent_eCu_phi_10x115_afterburned.csv"
        - "EXCLUSIVE/DIFFRACTIVE_PHI/eSTARlight/eSTARlight1.2.0-1.0_coherent_eRu_phi_10x115_afterburned.csv"

EXCLUSIVE:DIFFRACTIVE_PHI:timings:
  extends: .timings
  needs: 
    - EXCLUSIVE:DIFFRACTIVE_PHI:nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DIFFRACTIVE_PHI/Sartre_Coherent.csv"
        - "EXCLUSIVE/DIFFRACTIVE_PHI/Sartre_Coherent_q2_15.csv"
        - "EXCLUSIVE/DIFFRACTIVE_PHI/Sartre_Incoherent.csv"
        - "EXCLUSIVE/DIFFRACTIVE_PHI/sartre1.39-1.0_coherent_phi_eAu_bsat_10x100.csv"
        - "EXCLUSIVE/DIFFRACTIVE_PHI/eSTARlight/eSTARlight1.2.0-1.0_coherent_eCu_phi_10x115_afterburned.csv"
        - "EXCLUSIVE/DIFFRACTIVE_PHI/eSTARlight/eSTARlight1.2.0-1.0_coherent_eRu_phi_10x115_afterburned.csv"

EXCLUSIVE:DIFFRACTIVE_PHI:collect:
  extends: .collect
  needs: 
    - EXCLUSIVE:DIFFRACTIVE_PHI:timings
