.eAu_10x100_variables: &eAu_10x100_variables
  DETECTOR_CONFIG_OVERRIDE: "epic_craterlake_without_zdc"
  EBEAM_OVERRIDE: "10"
  PBEAM_OVERRIDE: "100_Au197"

DIS:eAu:10x100:nevents:
  variables:
    <<: *eAu_10x100_variables
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/eAu/10x100/BeAGLE1.03.02-2.0_DIS_eAu_10x100_q2_1to10.csv"
        - "DIS/eAu/10x100/BeAGLE1.03.02-2.0_DIS_eAu_10x100_q2_10to100.csv"

DIS:eAu:10x100:timings:
  variables:
    <<: *eAu_10x100_variables
  extends: .timings
  needs:
    - DIS:eAu:10x100:nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/eAu/10x100/BeAGLE1.03.02-2.0_DIS_eAu_10x100_q2_1to10.csv"
        - "DIS/eAu/10x100/BeAGLE1.03.02-2.0_DIS_eAu_10x100_q2_10to100.csv"

DIS:eAu:10x100:collect:
  extends: .collect
  needs:
    - DIS:eAu:10x100:timings
