.eCu_10x115_variables: &eCu_10x115_variables
  EBEAM_OVERRIDE: "10"
  PBEAM_OVERRIDE: "115_Cu63"

DIS:eCu:10x115:nevents:
  variables:
    <<: *eCu_10x115_variables
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/eCu/10x115/BeAGLE1.03.02-1.0_DIS_eCu_en_10x115.csv"
        - "DIS/eCu/10x115/BeAGLE1.03.02-1.0_DIS_eCu_ep_10x115.csv"

DIS:eCu:10x115:timings:
  variables:
    <<: *eCu_10x115_variables
  extends: .timings
  needs:
    - DIS:eCu:10x115:nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/eCu/10x115/BeAGLE1.03.02-1.0_DIS_eCu_en_10x115.csv"
        - "DIS/eCu/10x115/BeAGLE1.03.02-1.0_DIS_eCu_ep_10x115.csv"

DIS:eCu:10x115:collect:
  variables:
    <<: *eCu_10x115_variables
  extends: .collect
  needs:
    - DIS:eCu:10x115:timings
