include:
  - local: 'DIS/ep/CC/config.yml'
  - local: 'DIS/ep/NC/config.yml'
  - local: 'DIS/eAu/config.yml'
  - local: 'DIS/eCu/config.yml'
  - local: 'DIS/eH2/config.yml'
  - local: 'DIS/eHe3/config.yml'
  - local: 'DIS/eRu/config.yml'

DIS:collect:
  extends: .collect
  needs:
    - DIS:ep:CC:collect
    - DIS:ep:NC:collect
    - DIS:eAu:collect
    - DIS:eCu:collect
    - DIS:eH2:collect
    - DIS:eHe3:collect
    - DIS:eRu:collect