include:
  #- local: 'EXCLUSIVE/DIFFRACTIVE_JPSI/config.yml'
  #- local: 'EXCLUSIVE/DIFFRACTIVE_PHI/config.yml'
  #- local: 'EXCLUSIVE/DIFFRACTIVE_RHO/config.yml'
  - local: 'EXCLUSIVE/SPECTROSCOPY/config.yml'
  - local: 'EXCLUSIVE/DVCS/config.yml'
  - local: 'EXCLUSIVE/TCS/config.yml'
  - local: 'EXCLUSIVE/OMEGA/config.yml'
  - local: 'EXCLUSIVE/RHO/config.yml'

EXCLUSIVE:gzip:
  extends: .gzip
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DEMP.csv"
        - "EXCLUSIVE/DVCSD.csv"
        - "EXCLUSIVE/DVMP.csv"
        - "EXCLUSIVE/UPSILON.csv"
        - "EXCLUSIVE/omega.csv"
        - "EXCLUSIVE/x_y_psi.csv"

EXCLUSIVE:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DEMP.csv"
        - "EXCLUSIVE/DVCSD.csv"
        - "EXCLUSIVE/DVMP.csv"
        - "EXCLUSIVE/UPSILON.csv"
        - "EXCLUSIVE/omega.csv"
        - "EXCLUSIVE/x_y_psi.csv"

EXCLUSIVE:timings:
  extends: .timings
  needs: 
    - EXCLUSIVE:nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DEMP.csv"
        - "EXCLUSIVE/DVCSD.csv"
        - "EXCLUSIVE/DVMP.csv"
        - "EXCLUSIVE/UPSILON.csv"
        - "EXCLUSIVE/omega.csv"
        - "EXCLUSIVE/x_y_psi.csv"

EXCLUSIVE:collect:
  extends: .collect
  needs: 
    #- EXCLUSIVE:DIFFRACTIVE_JPSI:collect
    #- EXCLUSIVE:DIFFRACTIVE_PHI:collect
    #- EXCLUSIVE:DIFFRACTIVE_RHO:collect
    - EXCLUSIVE:SPECTROSCOPY:collect
    - EXCLUSIVE:DVCS:collect
    - EXCLUSIVE:TCS:collect
    - EXCLUSIVE:timings
