include:
  - local: 'EXCLUSIVE/DIFFRACTIVE_PHI/config.yml'
  - local: 'EXCLUSIVE/DVCS/config.yml'
  - local: 'EXCLUSIVE/TCS/config.yml'

EXCLUSIVE:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DEMP.csv"
        - "EXCLUSIVE/DVCSD.csv"
        - "EXCLUSIVE/DVMP.csv"
        - "EXCLUSIVE/OMEGA.csv"
        - "EXCLUSIVE/RHO.csv"
        - "EXCLUSIVE/UPSILON.csv"
        - "EXCLUSIVE/omega.csv"
        - "EXCLUSIVE/x_y_psi.csv"

EXCLUSIVE:timings:
  extends: .timings
  needs: 
    - EXCLUSIVE:nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DEMP.csv"
        - "EXCLUSIVE/DVCSD.csv"
        - "EXCLUSIVE/DVMP.csv"
        - "EXCLUSIVE/OMEGA.csv"
        - "EXCLUSIVE/RHO.csv"
        - "EXCLUSIVE/UPSILON.csv"
        - "EXCLUSIVE/omega.csv"
        - "EXCLUSIVE/x_y_psi.csv"

EXCLUSIVE:collect:
  extends: .collect
  needs: 
    - EXCLUSIVE:DIFFRACTIVE_PHI:collect
    - EXCLUSIVE:DVCS:collect
    - EXCLUSIVE:TCS:collect
    - EXCLUSIVE:timings
