EXCLUSIVE:DVCS:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DVCS/DVCS_5x41_hiDiv.csv"
        - "EXCLUSIVE/DVCS/DVCS_5x41_hiAcc.csv"
        - "EXCLUSIVE/DVCS/DVCS_10x100_hiDiv.csv"
        - "EXCLUSIVE/DVCS/DVCS_10x100_hiAcc.csv"
        - "EXCLUSIVE/DVCS/DVCS_18x275_hiDiv.csv"
        - "EXCLUSIVE/DVCS/DVCS_18x275_hiAcc.csv"
        - "EXCLUSIVE/DVCS/EpIC_v1.1.6-1.1_DVCS_BH_INT_10x130_hiAcc.csv"

EXCLUSIVE:DVCS:timings:
  extends: .timings
  needs: 
    - EXCLUSIVE:DVCS:nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DVCS/DVCS_5x41_hiDiv.csv"
        - "EXCLUSIVE/DVCS/DVCS_5x41_hiAcc.csv"
        - "EXCLUSIVE/DVCS/DVCS_10x100_hiDiv.csv"
        - "EXCLUSIVE/DVCS/DVCS_10x100_hiAcc.csv"
        - "EXCLUSIVE/DVCS/DVCS_18x275_hiDiv.csv"
        - "EXCLUSIVE/DVCS/DVCS_18x275_hiAcc.csv"
        - "EXCLUSIVE/DVCS/EpIC_v1.1.6-1.1_DVCS_BH_INT_10x130_hiAcc.csv"

EXCLUSIVE:DVCS:collect:
  extends: .collect
  needs: 
    - EXCLUSIVE:DVCS:timings
