EXCLUSIVE:TCS:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/TCS/TCS_5x41_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_5x41_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_5x41_hiAcc_novtx.csv"
        - "EXCLUSIVE/TCS/TCS_5x41_hiDiv_novtx.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiAcc_novtx.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiDiv_novtx.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiAcc_novtx.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiDiv_novtx.csv"

EXCLUSIVE:TCS:timings:
  extends: .timings
  needs: 
    - EXCLUSIVE:TCS:nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/TCS/TCS_5x41_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_5x41_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_5x41_hiAcc_novtx.csv"
        - "EXCLUSIVE/TCS/TCS_5x41_hiDiv_novtx.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiAcc_novtx.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiDiv_novtx.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiAcc_novtx.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiDiv_novtx.csv"

EXCLUSIVE:TCS:collect:
  extends: .collect
  needs: 
    - EXCLUSIVE:TCS:timings
