EXCLUSIVE:TCS:gzip:
  extends: .gzip
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/TCS/TCS_5x41_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_5x41_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiDiv.csv"

EXCLUSIVE:TCS:nevents:
  extends: .nevents
  needs:
    - EXCLUSIVE:TCS:gzip
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/TCS/TCS_5x41_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_5x41_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiDiv.csv"

EXCLUSIVE:TCS:timings:
  extends: .timings
  needs: 
    - EXCLUSIVE:TCS:nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/TCS/TCS_5x41_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_5x41_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_10x100_hiDiv.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiAcc.csv"
        - "EXCLUSIVE/TCS/TCS_18x275_hiDiv.csv"

EXCLUSIVE:TCS:collect:
  extends: .collect
  needs: 
    - EXCLUSIVE:TCS:timings
