include:
  - local: 'SIDIS/pythia6-eic/1.2.0/config.yml'
  - local: 'SIDIS/pythia6-eic/1.3.0/config.yml'

SIDIS:pythia6-eic:collect:
  extends: .collect
  needs:
    - SIDIS:pythia6-eic:1.2.0:collect
    - SIDIS:pythia6-eic:1.3.0:collect
