DIS:NC:5x41:gzip:
  extends: .gzip
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/5x41/minQ2=100/DIS_NC_5x41_minQ2=100.csv"
        - "DIS/NC/5x41/minQ2=10/DIS_NC_5x41_minQ2=10.csv"
        - "DIS/NC/5x41/minQ2=1/DIS_NC_5x41_minQ2=1.csv"

DIS:NC:5x41:nevents:
  extends: .nevents
  needs:
    - DIS:NC:5x41:gzip
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/5x41/minQ2=100/DIS_NC_5x41_minQ2=100.csv"
        - "DIS/NC/5x41/minQ2=10/DIS_NC_5x41_minQ2=10.csv"
        - "DIS/NC/5x41/minQ2=1/DIS_NC_5x41_minQ2=1.csv"

DIS:NC:5x41:timings:
  extends: .timings
  needs: 
    - DIS:NC:5x41:nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/5x41/minQ2=100/DIS_NC_5x41_minQ2=100.csv"
        - "DIS/NC/5x41/minQ2=10/DIS_NC_5x41_minQ2=10.csv"
        - "DIS/NC/5x41/minQ2=1/DIS_NC_5x41_minQ2=1.csv"

DIS:NC:5x41:collect:
  extends: .collect
  needs: 
    - DIS:NC:5x41:timings
