DIS:ep:NC:5x41:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/ep/NC/5x41/DIS_NC_5x41_minQ2=100.csv"
        - "DIS/ep/NC/5x41/DIS_NC_5x41_minQ2=10.csv"
        - "DIS/ep/NC/5x41/DIS_NC_5x41_minQ2=1.csv"

DIS:ep:NC:5x41:timings:
  extends: .timings
  needs: 
    - DIS:ep:NC:5x41:nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/ep/NC/5x41/DIS_NC_5x41_minQ2=100.csv"
        - "DIS/ep/NC/5x41/DIS_NC_5x41_minQ2=10.csv"
        - "DIS/ep/NC/5x41/DIS_NC_5x41_minQ2=1.csv"

DIS:ep:NC:5x41:collect:
  extends: .collect
  needs: 
    - DIS:ep:NC:5x41:timings
