EXCLUSIVE:DEMP:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.2_5x41_pi+.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.2_10x100_pi+.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.2_18x275_pi+.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.2_5x41_K+Lambda.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.3_10x130_K+Lambda.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.3_10x130_pi+.csv"
        

EXCLUSIVE:DEMP:timings:
  extends: .timings
  needs: 
    - EXCLUSIVE:DEMP:nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.2_5x41_pi+.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.2_10x100_pi+.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.2_18x275_pi+.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.2_5x41_K+Lambda.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.3_10x130_K+Lambda.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.2.3_10x130_pi+.csv"

EXCLUSIVE:DEMP:collect:
  extends: .collect
  needs: 
    - EXCLUSIVE:DEMP:timings
