EXCLUSIVE:DEMP:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_5x41_pi+.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_10x100_pi+.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_5x41_K+Lambda.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_10x100_K+Lambda.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_5x41_K+Sigma0.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_10x100_K+Sigma0.csv"

EXCLUSIVE:DEMP:timings:
  extends: .timings
  needs: 
    - EXCLUSIVE:DEMP:nevents
  parallel:
    matrix:
      - DATA:
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_5x41_pi+.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_10x100_pi+.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_5x41_K+Lambda.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_10x100_K+Lambda.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_5x41_K+Sigma0.csv"
        - "EXCLUSIVE/DEMP/DEMPgen-1.1.0_10x100_K+Sigma0.csv"

EXCLUSIVE:DEMP:collect:
  extends: .collect
  needs: 
    - EXCLUSIVE:DEMP:timings
