DIS:CC:10x275:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/CC/10x275/minQ2=1000/DIS_CC_10x275_minQ2=1000.csv"
        - "DIS/CC/10x275/minQ2=100/DIS_CC_10x275_minQ2=100.csv"

DIS:CC:10x275:timings:
  extends: .timings
  needs: 
    - DIS:CC:10x275:nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/CC/10x275/minQ2=1000/DIS_CC_10x275_minQ2=1000.csv"
        - "DIS/CC/10x275/minQ2=100/DIS_CC_10x275_minQ2=100.csv"

DIS:CC:10x275:collect:
  extends: .collect
  needs: 
    - DIS:CC:10x275:timings
