DIS:NC:5x100:gzip:
  extends: .gzip
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/5x100/minQ2=1000/DIS_NC_5x100_minQ2=1000.csv"
        - "DIS/NC/5x100/minQ2=100/DIS_NC_5x100_minQ2=100.csv"
        - "DIS/NC/5x100/minQ2=10/DIS_NC_5x100_minQ2=10.csv"
        - "DIS/NC/5x100/minQ2=1/DIS_NC_5x100_minQ2=1.csv"

DIS:NC:5x100:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/5x100/minQ2=1000/DIS_NC_5x100_minQ2=1000.csv"
        - "DIS/NC/5x100/minQ2=100/DIS_NC_5x100_minQ2=100.csv"
        - "DIS/NC/5x100/minQ2=10/DIS_NC_5x100_minQ2=10.csv"
        - "DIS/NC/5x100/minQ2=1/DIS_NC_5x100_minQ2=1.csv"

DIS:NC:5x100:timings:
  extends: .timings
  needs: 
    - DIS:NC:5x100:nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/NC/5x100/minQ2=1000/DIS_NC_5x100_minQ2=1000.csv"
        - "DIS/NC/5x100/minQ2=100/DIS_NC_5x100_minQ2=100.csv"
        - "DIS/NC/5x100/minQ2=10/DIS_NC_5x100_minQ2=10.csv"
        - "DIS/NC/5x100/minQ2=1/DIS_NC_5x100_minQ2=1.csv"

DIS:NC:5x100:collect:
  extends: .collect
  needs: 
    - DIS:NC:5x100:timings
