DIS:eHe3:10x110:nevents:
  extends: .nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/eHe3/10x110/BeAGLE1.03.02-1.2_DIS_eHe3_10x110_q2_2to10.csv"
        - "DIS/eHe3/10x110/BeAGLE1.03.02-1.2_DIS_eHe3_10x110_q2_10to100.csv"
        - "DIS/eHe3/10x110/BeAGLE1.03.02-1.2_DIS_eHe3_10x110_q2_100to10000.csv"

DIS:eHe3:10x110:timings:
  extends: .timings
  needs:
    - DIS:eHe3:10x110:nevents
  parallel:
    matrix:
      - DATA:
        - "DIS/eHe3/10x110/BeAGLE1.03.02-1.2_DIS_eHe3_10x110_q2_2to10.csv"
        - "DIS/eHe3/10x110/BeAGLE1.03.02-1.2_DIS_eHe3_10x110_q2_10to100.csv"
        - "DIS/eHe3/10x110/BeAGLE1.03.02-1.2_DIS_eHe3_10x110_q2_100to10000.csv"

DIS:eHe3:10x110:collect:
  extends: .collect
  needs:
    - DIS:eHe3:10x110:timings
